# Generated by Django 4.1.7 on 2023-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_salas_options_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='chatapp'),
        ),
    ]
