# Generated by Django 4.1.7 on 2023-06-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_salas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgsalas'),
        ),
    ]
