# Generated by Django 4.1.7 on 2023-06-05 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0004_alter_salas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_c', to='chatapp.salas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_c', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sala_c',
                'verbose_name_plural': 'Salas_c',
            },
        ),
    ]
