# Generated by Django 4.1.7 on 2023-06-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_salas_password_salas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='password',
        ),
    ]
